// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";

// Import and reexport all reducer arg types
import { AddCells } from "./add_cells_reducer.ts";
export { AddCells };
import { ResetGrid } from "./reset_grid_reducer.ts";
export { ResetGrid };
import { UpdateGrid } from "./update_grid_reducer.ts";
export { UpdateGrid };

// Import and reexport all table handle types
import { GridTableHandle } from "./grid_table.ts";
export { GridTableHandle };
import { GridInfoTableHandle } from "./grid_info_table.ts";
export { GridInfoTableHandle };
import { PreviousGridTableHandle } from "./previous_grid_table.ts";
export { PreviousGridTableHandle };
import { UpdateGridScheduleTableHandle } from "./update_grid_schedule_table.ts";
export { UpdateGridScheduleTableHandle };

// Import and reexport all types
import { Grid } from "./grid_type.ts";
export { Grid };
import { GridInfo } from "./grid_info_type.ts";
export { GridInfo };
import { PreviousGrid } from "./previous_grid_type.ts";
export { PreviousGrid };
import { UpdateGridSchedule } from "./update_grid_schedule_type.ts";
export { UpdateGridSchedule };

const REMOTE_MODULE = {
  tables: {
    grid: {
      tableName: "grid",
      rowType: Grid.getTypeScriptAlgebraicType(),
      primaryKey: "gridid",
    },
    grid_info: {
      tableName: "grid_info",
      rowType: GridInfo.getTypeScriptAlgebraicType(),
      primaryKey: "gridid",
    },
    previous_grid: {
      tableName: "previous_grid",
      rowType: PreviousGrid.getTypeScriptAlgebraicType(),
      primaryKey: "gridid",
    },
    update_grid_schedule: {
      tableName: "update_grid_schedule",
      rowType: UpdateGridSchedule.getTypeScriptAlgebraicType(),
      primaryKey: "scheduled_id",
    },
  },
  reducers: {
    add_cells: {
      reducerName: "add_cells",
      argsType: AddCells.getTypeScriptAlgebraicType(),
    },
    reset_grid: {
      reducerName: "reset_grid",
      argsType: ResetGrid.getTypeScriptAlgebraicType(),
    },
    update_grid: {
      reducerName: "update_grid",
      argsType: UpdateGrid.getTypeScriptAlgebraicType(),
    },
  },
  // Constructors which are used by the DbConnectionImpl to
  // extract type information from the generated RemoteModule.
  //
  // NOTE: This is not strictly necessary for `eventContextConstructor` because
  // all we do is build a TypeScript object which we could have done inside the
  // SDK, but if in the future we wanted to create a class this would be
  // necessary because classes have methods, so we'll keep it.
  eventContextConstructor: (imp: DbConnectionImpl, event: Event<Reducer>) => {
    return {
      ...(imp as DbConnection),
      event
    }
  },
  dbViewConstructor: (imp: DbConnectionImpl) => {
    return new RemoteTables(imp);
  },
  reducersConstructor: (imp: DbConnectionImpl, setReducerFlags: SetReducerFlags) => {
    return new RemoteReducers(imp, setReducerFlags);
  },
  setReducerFlagsConstructor: () => {
    return new SetReducerFlags();
  }
}

// A type representing all the possible variants of a reducer.
export type Reducer = never
| { name: "AddCells", args: AddCells }
| { name: "ResetGrid", args: ResetGrid }
| { name: "UpdateGrid", args: UpdateGrid }
;

export class RemoteReducers {
  constructor(private connection: DbConnectionImpl, private setCallReducerFlags: SetReducerFlags) {}

  addCells(cellsToAdd: number[]) {
    const __args = { cellsToAdd };
    let __writer = new BinaryWriter(1024);
    AddCells.getTypeScriptAlgebraicType().serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("add_cells", __argsBuffer, this.setCallReducerFlags.addCellsFlags);
  }

  onAddCells(callback: (ctx: ReducerEventContext, cellsToAdd: number[]) => void) {
    this.connection.onReducer("add_cells", callback);
  }

  removeOnAddCells(callback: (ctx: ReducerEventContext, cellsToAdd: number[]) => void) {
    this.connection.offReducer("add_cells", callback);
  }

  resetGrid() {
    this.connection.callReducer("reset_grid", new Uint8Array(0), this.setCallReducerFlags.resetGridFlags);
  }

  onResetGrid(callback: (ctx: ReducerEventContext) => void) {
    this.connection.onReducer("reset_grid", callback);
  }

  removeOnResetGrid(callback: (ctx: ReducerEventContext) => void) {
    this.connection.offReducer("reset_grid", callback);
  }

  updateGrid(args: UpdateGridSchedule) {
    const __args = { args };
    let __writer = new BinaryWriter(1024);
    UpdateGrid.getTypeScriptAlgebraicType().serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("update_grid", __argsBuffer, this.setCallReducerFlags.updateGridFlags);
  }

  onUpdateGrid(callback: (ctx: ReducerEventContext, args: UpdateGridSchedule) => void) {
    this.connection.onReducer("update_grid", callback);
  }

  removeOnUpdateGrid(callback: (ctx: ReducerEventContext, args: UpdateGridSchedule) => void) {
    this.connection.offReducer("update_grid", callback);
  }

}

export class SetReducerFlags {
  addCellsFlags: CallReducerFlags = 'FullUpdate';
  addCells(flags: CallReducerFlags) {
    this.addCellsFlags = flags;
  }

  resetGridFlags: CallReducerFlags = 'FullUpdate';
  resetGrid(flags: CallReducerFlags) {
    this.resetGridFlags = flags;
  }

  updateGridFlags: CallReducerFlags = 'FullUpdate';
  updateGrid(flags: CallReducerFlags) {
    this.updateGridFlags = flags;
  }

}

export class RemoteTables {
  constructor(private connection: DbConnectionImpl) {}

  get grid(): GridTableHandle {
    return new GridTableHandle(this.connection.clientCache.getOrCreateTable<Grid>(REMOTE_MODULE.tables.grid));
  }

  get gridInfo(): GridInfoTableHandle {
    return new GridInfoTableHandle(this.connection.clientCache.getOrCreateTable<GridInfo>(REMOTE_MODULE.tables.grid_info));
  }

  get previousGrid(): PreviousGridTableHandle {
    return new PreviousGridTableHandle(this.connection.clientCache.getOrCreateTable<PreviousGrid>(REMOTE_MODULE.tables.previous_grid));
  }

  get updateGridSchedule(): UpdateGridScheduleTableHandle {
    return new UpdateGridScheduleTableHandle(this.connection.clientCache.getOrCreateTable<UpdateGridSchedule>(REMOTE_MODULE.tables.update_grid_schedule));
  }
}

export class SubscriptionBuilder extends SubscriptionBuilderImpl<RemoteTables, RemoteReducers, SetReducerFlags> { }

export class DbConnection extends DbConnectionImpl<RemoteTables, RemoteReducers, SetReducerFlags> {
  static builder = (): DbConnectionBuilder<DbConnection, ErrorContext, SubscriptionEventContext> => {
    return new DbConnectionBuilder<DbConnection, ErrorContext, SubscriptionEventContext>(REMOTE_MODULE, (imp: DbConnectionImpl) => imp as DbConnection);
  }
  subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  }
}

export type EventContext = EventContextInterface<RemoteTables, RemoteReducers, SetReducerFlags, Reducer>;
export type ReducerEventContext = ReducerEventContextInterface<RemoteTables, RemoteReducers, SetReducerFlags, Reducer>;
export type SubscriptionEventContext = SubscriptionEventContextInterface<RemoteTables, RemoteReducers, SetReducerFlags>;
export type ErrorContext = ErrorContextInterface<RemoteTables, RemoteReducers, SetReducerFlags>;
